apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: djncaptcha
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: djncaptcha-tomcat
    newName: rg.fr-par.scw.cloud/djnd/djncaptcha-tomcat
    newTag: 'd9e94c0fef7d892fdb35ac9463005f4140c4f3ce'
  - name: djncaptcha-nginx
    newName: rg.fr-par.scw.cloud/djnd/djncaptcha-nginx
    newTag: 'd9e94c0fef7d892fdb35ac9463005f4140c4f3ce'
