apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: djncaptcha
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: djncaptcha-tomcat
    newName: rg.fr-par.scw.cloud/djnd/djncaptcha-tomcat
    newTag: '07373cc9c88417f0d04cee6a2e3a6885ea0853f7'
  - name: djncaptcha-nginx
    newName: rg.fr-par.scw.cloud/djnd/djncaptcha-nginx
    newTag: '07373cc9c88417f0d04cee6a2e3a6885ea0853f7'
