apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: djncaptcha
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: djncaptcha-tomcat
    newName: rg.fr-par.scw.cloud/djnd/djncaptcha-tomcat
    newTag: 'cf3c121620c444358611d6d879aabb9e79f7b2f1'
  - name: djncaptcha-nginx
    newName: rg.fr-par.scw.cloud/djnd/djncaptcha-nginx
    newTag: 'cf3c121620c444358611d6d879aabb9e79f7b2f1'
