version: '3'

services:
  tomcat:
    build: ./tomcat
    volumes:
      - ./tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml:delegated,rw
      - ./tomcat/conf/web.xml:/usr/local/tomcat/conf/web.xml:delegated,rw
    # ports:
    #   - "8080:8080"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:delegated,rw
      - ./nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf:delegated,rw
      - ./nginx/html:/usr/share/nginx/html:delegated,rw
    ports:
      - "8000:80"
    depends_on:
      - tomcat
